### ISSUE TITLE
SC 100

### ISSUE THREAD

**Issue by jgmuchiri** [Lambda-School-Labs/mission-control-be#109]
https://github.com/Lambda-School-Labs/mission-control-be/blob/da9625015eda021dbede6ecf5a2c28cbd47c0bed/apollo/src/datasources/CodeClimateAPI.js#L8

RE: https://lambda-school-labs.github.io/labs-engineering-standards/topics/security/#sc-100-never-commit-secrets

**Comment by RobertDGordon** [comment]
This was removed and added to environment variables with PR #107 Update the Environment Variables.
