### ISSUE TITLE
Firefox: AuthSdk Error

### ISSUE THREAD

**Issue by gebhartn** [Lambda-School-Labs/mission-control-be#56]
#### AuthSdkError: Unable to retrieve OAuth redirect params cookie

![2020-01-25-174913_1838x457_scrot](https://user-images.githubusercontent.com/52334965/73129534-329f4180-3f9b-11ea-8900-3176c1be743e.png)

Sometimes refreshing the page allows a connection to occur, but it's consistently inconsistent and happens only in Firefox. Fails with both the developer OKTA credentials as well as the Lambda-dev credentials.

OS: Arch Linux 64bit
Firefox: 72.0.2 64bit

**Comment by KAfable** [comment]
Looks like this was fixed per https://github.com/okta/okta-oidc-js/issues/654
